### ISSUE TITLE
deleted entries in seo_url prevent redirects from working

### ISSUE THREAD

**Issue by jeboehm** [tinect/TinectRedirects#13]
Example:
In table seo_url uri /shop/ with is_deleted set to 1.
In table tinect_redirect_redirects /shop/ to any destination.

When you call /shop/ you'll see http error 404, and no redirection is sent.

**Comment by tinect** [comment]
The example misses, that the linked entity is removed, too, isn't it?

**Comment by jeboehm** [comment]
I'm not completely sure under what circumstances the is_deleted flag is set.
